on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: node runner
        uses: actions/setup-node@v1
        with:
          node-version: 13.13
      - name: lint inspect
        uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      - run: |
          yarn install
          yarn lint
          yarn testci
