on: 
  pull_request:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node runner
        uses: actions/setup-node@v1
        with: 
          node-version: 13.13
      - name : install packages  
        run : npm install
